import { HOME, MANAGE_USER, PROFILES, SETTINGS } from './pages';

export const ROLES = {
  ADMIN: 'ADMIN',
  MAINTAINER: 'MAINTAINER',
  USER: 'USER',
};

export const PAGE_AUTH = {
  [ROLES.ADMIN]: [HOME, MANAGE_USER, PROFILES, SETTINGS],
  [ROLES.MAINTAINER]: [HOME, MANAGE_USER, PROFILES],
  [ROLES.USER]: [HOME, PROFILES],
};
